import {
  parseScenarioManifest,
  type ScenarioManifest,
} from "./scenario-manifest.ts";

const marker = "ap2-sharepoint-trusted-version-fixture";

export const SHAREPOINT_TRUSTED_VERSION_LIFECYCLE_SCENARIO =
  parseScenarioManifest({
    schemaVersion: 2,
    id: "sharepoint-trusted-version-lifecycle",
    title: "SharePoint trusted-version lifecycle",
    summary:
      "The API managed identity creates one harmless trusted text version, writes one harmless changed version, proves exact ordered version bytes, and removes the active run artifacts.",
    actors: [
      {
        id: "sharepoint-producer-app",
        label: "SharePoint producer application",
        kind: "application",
        summary: "Uses the existing API managed identity to perform the exact SharePoint operations.",
      },
      {
        id: "future-purview-detector",
        label: "Future Purview detector",
        kind: "application",
        summary: "Reserved for a later independent audit observation; unused by this lifecycle.",
      },
      {
        id: "future-human-learner",
        label: "Future human learner",
        kind: "human",
        summary: "Reserved for a later learner observation; no learner action occurs here.",
      },
      {
        id: "trusted-version-cleanup-owner",
        label: "Trusted-version orchestrator and cleanup owner",
        kind: "orchestrator",
        summary: "Owns the one-shot journal, receipt boundary, marker-bound cleanup, and terminal active-absence reconciliation.",
      },
    ],
    roles: {
      evidenceProducer: "trusted-version-cleanup-owner",
      workloadActor: "sharepoint-producer-app",
      learner: "future-human-learner",
      detector: "future-purview-detector",
    },
    authentication: [
      {
        actorId: "sharepoint-producer-app",
        transport: "managed-identity",
        summary: "Existing API managed identity with the already granted Sites.ReadWrite.All application role.",
      },
      {
        actorId: "trusted-version-cleanup-owner",
        transport: "operator-session",
        summary: "Existing AP2 operator authorization starts and owns cleanup for the bounded route; the managed identity remains the SharePoint transport.",
      },
    ],
    trigger: { kind: "staged" },
    detection: { kind: "independent" },
    prerequisites: [
      {
        id: "fixed-sharepoint-drive",
        kind: "resource",
        summary: "The configured drive is the established tenant-local AP2 SharePoint document library.",
        requiredState: "Exact drive identity and document-library type are verified before mutation.",
      },
      {
        id: "fixed-managed-identity-authority",
        kind: "permission",
        summary: "The API managed identity has the existing Sites.ReadWrite.All Graph application role.",
        requiredState: "Complete app-role reads and a fresh managed-identity token agree.",
      },
      {
        id: "exclusive-one-shot-journal",
        kind: "evidence",
        summary: "The unique marker, expiry, ownership, and no-replay contract are frozen.",
        requiredState: "The exact run-folder path is absent before the first mutation.",
      },
    ],
    operations: [
      {
        key: "schedule-trusted-version-expiry",
        phase: "setup",
        capability: "expiry.schedule",
        effect: "mutation",
        ownerActorId: "trusted-version-cleanup-owner",
        marker,
        summary: "Reserve the one-shot marker and freeze its expiry before SharePoint mutation.",
      },
      {
        key: "create-trusted-version-folder",
        phase: "setup",
        capability: "sharepoint.folder-create",
        effect: "mutation",
        ownerActorId: "sharepoint-producer-app",
        marker,
        dependsOnOperationKeys: ["schedule-trusted-version-expiry"],
        summary: "Create the exact marker-bound run folder once.",
      },
      {
        key: "create-trusted-version-one",
        phase: "evidence",
        capability: "sharepoint.file-create",
        effect: "mutation",
        ownerActorId: "sharepoint-producer-app",
        marker,
        dependsOnOperationKeys: ["create-trusted-version-folder"],
        summary: "Create one fixed harmless text file and prove the trusted version-one bytes.",
      },
      {
        key: "write-trusted-version-two",
        phase: "evidence",
        capability: "sharepoint.file-update",
        effect: "mutation",
        ownerActorId: "sharepoint-producer-app",
        marker,
        dependsOnOperationKeys: ["create-trusted-version-one"],
        summary: "Write exactly one fixed harmless changed version.",
      },
      {
        key: "read-ordered-version-history",
        phase: "evidence",
        capability: "sharepoint.version-history-read",
        effect: "read",
        ownerActorId: "sharepoint-producer-app",
        dependsOnOperationKeys: ["write-trusted-version-two"],
        summary: "Read one capped, unpaged version list in platform order.",
      },
      {
        key: "read-exact-version-bytes",
        phase: "evidence",
        capability: "sharepoint.version-content-read",
        effect: "read",
        ownerActorId: "sharepoint-producer-app",
        dependsOnOperationKeys: ["read-ordered-version-history"],
        summary: "Read and digest the exact trusted and changed bytes.",
      },
      {
        key: "delete-trusted-version-file",
        phase: "cleanup",
        capability: "sharepoint.file-delete",
        effect: "mutation",
        ownerActorId: "trusted-version-cleanup-owner",
        marker,
        dependsOnOperationKeys: ["read-exact-version-bytes"],
        summary: "Delete only the exact retained run-owned file.",
      },
      {
        key: "delete-trusted-version-folder",
        phase: "cleanup",
        capability: "sharepoint.folder-delete",
        effect: "mutation",
        ownerActorId: "trusted-version-cleanup-owner",
        marker,
        dependsOnOperationKeys: ["delete-trusted-version-file"],
        summary: "Delete only the exact run folder after proving it empty.",
      },
      {
        key: "remove-trusted-version-expiry",
        phase: "cleanup",
        capability: "expiry.remove",
        effect: "mutation",
        ownerActorId: "trusted-version-cleanup-owner",
        marker,
        dependsOnOperationKeys: ["delete-trusted-version-folder"],
        summary: "Close the one-shot expiry contract after terminal absence.",
      },
      {
        key: "reconcile-trusted-version-absence",
        phase: "evidence",
        capability: "artifact.read-exact",
        effect: "read",
        ownerActorId: "trusted-version-cleanup-owner",
        dependsOnOperationKeys: ["remove-trusted-version-expiry"],
        summary: "Prove the exact active file and run-folder paths are absent and the one-shot expiry is closed.",
      },
    ],
    resources: [],
    permissions: [
      {
        id: "producer-sites-read-write",
        kind: "graph-app-role",
        name: "Sites.ReadWrite.All",
        actorId: "sharepoint-producer-app",
        scope: "Microsoft Graph application",
        purpose: "Operate only the exact marker-bound AP2 SharePoint lifecycle.",
        mode: "retained",
        retentionRationale: "Pre-existing hosted API capability; no permission mutation is part of this run.",
      },
    ],
    evidence: {
      staging: "The product route binds exact version-one and version-two bytes to one ordered version history before cleanup.",
      learnerReceives: "No learner receives or views the artifact in this lifecycle.",
      artifacts: [
        {
          id: "trusted-version-history",
          kind: "sharepoint-version-history",
          authenticity: "platform-native",
          state: "observed",
          learnerVisibility: "not-proven",
          sourceOperationKey: "write-trusted-version-two",
          observation: {
            operationKey: "read-exact-version-bytes",
            proofReference:
              "canonical:sharepoint-trusted-version-lifecycle/exact-version-digests",
          },
          claim: "SharePoint returned two ordered versions whose exact bytes matched the fixed trusted and changed payloads.",
          semanticClaims: ["sharepoint-trusted-version-staged"],
          retention: "ephemeral",
        },
      ],
    },
    learner: {
      task: "Later correlate the sanitized producer/version receipt with an independently observed audit record.",
      expectedInterpretation: "The producer-side version lifecycle is authentic; learner visibility and audit attribution remain separate claims.",
      completionState: "not-run",
      evidenceArtifactIds: ["trusted-version-history"],
    },
    responseActions: [],
    lifecycle: {
      expiresAt: "2026-12-31T23:59:59Z",
      cleanupOwnerActorId: "trusted-version-cleanup-owner",
      cleanupOperationKeys: [
        "delete-trusted-version-file",
        "delete-trusted-version-folder",
        "remove-trusted-version-expiry",
      ],
      retainedArtifacts: [],
    },
    cost: {
      currency: "USD",
      laneMaximum: 0,
      conservativeDurationHours: 1,
      assumption: "Existing licensed Microsoft 365 and hosted API services only.",
    },
  } satisfies ScenarioManifest);
